### ISSUE TITLE
 ERROR  Error watching file for changes: EMFILE

### ISSUE THREAD

**Issue by loretoparisi** [gitpoint/git-point#188]
```
Signing Identity:     "-"

    /usr/bin/codesign --force --sign - --timestamp=none /Users/loretoparisi/Documents/MyProjects/git-point/ios/build/Build/Products/Debug-iphonesimulator/GitPoint.app

 ERROR  Error watching file for changes: EMFILE
{"code":"EMFILE","errno":"EMFILE","syscall":"Error watching file for changes:","filename":null}
Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:1022:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1406:11)
Loading dependency graph...

Loading dependency graph...

** BUILD SUCCEEDED **


Installing build/Build/Products/Debug-iphonesimulator/GitPoint.app
Launching com.houssein.GitPoint
com.houssein.GitPoint: 56272
error Command failed with exit code 1.
```

I solved this

```
brew install --HEAD watchman
```

but I'm not sure that is the right way.

**Comment by housseindjirdeh** [comment]
Hi @loretoparisi 👋 

Are you using macOS? IF that's the case you do [need to install watchman](https://facebook.github.io/react-native/docs/getting-started.html#node-watchman) so I think you did the right thing :)

**Comment by loretoparisi** [comment]
@housseindjirdeh yes thanks closing this then!
