### ISSUE TITLE
Cannot get the app to run in the iOS simulator

### ISSUE THREAD

**Issue by frankdilo** [gitpoint/git-point#52]
Hi, thanks for this amazing project. I wanted to contribute in some way, but can't get the project to run since I am having this error in the packager:

```
error: bundling: UnableToResolveError: Unable to resolve module `config` from `/Users/frankdilo/projects/git-point/App.js`: Module does not exist in the module map or in these directories:
  /Users/frankdilo/projects/git-point/node_modules

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.
    at ResolutionRequest._resolveNodeDependency (/Users/frankdilo/projects/git-point/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:394:11)
    at tryResolveSync (/Users/frankdilo/projects/git-point/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:136:20)
    at tryResolveSync (/Users/frankdilo/projects/git-point/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:66:12)
    at ResolutionRequest.resolveDependency (/Users/frankdilo/projects/git-point/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:134:22)
    at dependencyNames.map.name (/Users/frankdilo/projects/git-point/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:145:59)
    at Array.map (native)
    at ResolutionRequest.resolveModuleDependencies (/Users/frankdilo/projects/git-point/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:145:42)
    at Promise.resolve.then (/Users/frankdilo/projects/git-point/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:169:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
Bundling `index.ios.js`  25.0% (1/2), failed.
```

**Comment by housseindjirdeh** [comment]
Thank you so much :) I'm glad you like the project and I can't tell you how much I appreciate your . willingness to contribute.

Yeah this used to happen to me from time to time. Can you try running `yarn start -- --reset-cache` and then `yarn run ios` to get the simulator up and running? If that doesn't work can you please try steps 1-3 in the logs there? Please let me know if either fixes the problem.

**Comment by frankdilo** [comment]
It worked, thanks a lot!
