### ISSUE TITLE
[1.4.1] App crash when click on view source if disconnected

### ISSUE THREAD

**Issue by rancidfrog** [gitpoint/git-point#668]
When you click on, for example git-point repository, "View Code" and you are not connected app crashes: 
```

12-19 11:20:58.082 31509  1423 E ReactNativeJS: undefined is not an object (evaluating 'this.props.repository.contents_url.replace')
12-19 11:20:58.110 31509  1427 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
12-19 11:20:58.110 31509  1427 E AndroidRuntime: Process: com.gitpoint, PID: 31509
12-19 11:20:58.110 31509  1427 E AndroidRuntime: com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 'this.props.repository.contents_url.replace'), stack:
12-19 11:20:58.110 31509  1427 E AndroidRuntime: value@1247:2800
12-19 11:20:58.110 31509  1427 E AndroidRuntime: notifyAll@157:38769
12-19 11:20:58.110 31509  1427 E AndroidRuntime: close@157:20099
12-19 11:20:58.110 31509  1427 E AndroidRuntime: closeAll@157:4141
12-19 11:20:58.110 31509  1427 E AndroidRuntime: perform@157:3571
12-19 11:20:58.110 31509  1427 E AndroidRuntime: perform@157:3484
12-19 11:20:58.110 31509  1427 E AndroidRuntime: perform@157:4728
12-19 11:20:58.110 31509  1427 E AndroidRuntime: $o@157:4889
12-19 11:20:58.110 31509  1427 E AndroidRuntime: closeAll@157:4141
12-19 11:20:58.110 31509  1427 E AndroidRuntime: perform@157:3571
12-19 11:20:58.110 31509  1427 E AndroidRuntime: batchedUpdates@157:18574
12-19 11:20:58.110 31509  1427 E AndroidRuntime: Ce@156:10516
12-19 11:20:58.110 31509  1427 E AndroidRuntime: Q@156:6049
12-19 11:20:58.110 31509  1427 E AndroidRuntime: K@156:6111
12-19 11:20:58.110 31509  1427 E AndroidRuntime: _receiveRootNodeIDEvent@156:28850
12-19 11:20:58.110 31509  1427 E AndroidRuntime: receiveTouches@156:29230
12-19 11:20:58.110 31509  1427 E AndroidRuntime: value@69:2975
12-19 11:20:58.110 31509  1427 E AndroidRuntime: <unknown>@69:280
12-19 11:20:58.110 31509  1427 E AndroidRuntime: value@69:2426
12-19 11:20:58.110 31509  1427 E AndroidRuntime: callFunctionReturnFlushedQueue@69:252
12-19 11:20:58.110 31509  1427 E AndroidRuntime:
12-19 11:20:58.110 31509  1427 E AndroidRuntime:        at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:56)
12-19 11:20:58.110 31509  1427 E AndroidRuntime:        at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:40)
12-19 11:20:58.110 31509  1427 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-19 11:20:58.110 31509  1427 E AndroidRuntime:        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:363)
12-19 11:20:58.110 31509  1427 E AndroidRuntime:        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
12-19 11:20:58.110 31509  1427 E AndroidRuntime:        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
12-19 11:20:58.110 31509  1427 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
12-19 11:20:58.110 31509  1427 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
12-19 11:20:58.110 31509  1427 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
12-19 11:20:58.110 31509  1427 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
12-19 11:20:58.110 31509  1427 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
12-19 11:20:58.110 31509  1427 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:761)
12-19 11:20:58.110 31509  1427 D AppTracker: App Event: crash
12-19 11:20:58.118  1440  2984 W ActivityManager:   Force finishing activity com.gitpoint/.MainActivity
12-19 11:20:58.127  1440  2984 D ActivityTrigger: ActivityTrigger activityPauseTrigger
12-19 11:20:58.130 31509  1427 I Process : Sending signal. PID: 31509 SIG: 9

12-19 11:20:58.208  1440  2076 W InputDispatcher: channel '609d49a com.gitpoint/com.gitpoint.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
12-19 11:20:58.208  1440  2076 E InputDispatcher: channel '609d49a com.gitpoint/com.gitpoint.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
12-19 11:20:58.262  1440  1457 D EmbryoManager: prepare com.gitpoint
12-19 11:20:58.262  1440  1457 I ActivityManager: Process com.gitpoint (pid 31509) has died
12-19 11:20:58.262  1440  1457 D ActivityManager: get process top duration : com.gitpoint, duration : 4553
12-19 11:20:58.262  1440  1457 D ActivityManager: cleanUpApplicationRecord -- 31509
12-19 11:20:58.263  1440  2985 D GraphicsStats: Buffer count: 13
12-19 11:20:58.264  1440  3003 I WindowManager: WIN DEATH: Window{609d49a u0 com.gitpoint/com.gitpoint.MainActivity}
12-19 11:20:58.264  1440  3003 W InputDispatcher: Attempted to unregister already unregistered input channel '609d49a com.gitpoint/com.gitpoint.MainActivity (server)'

```

**Comment by chinesedfan** [comment]
@rancidfrog What do you mean about "disconnected"? Networks? I try to enter the repository screen, turn off networks, and click "View Code". Just a white blank screen is there without crash.

But the above log really shows the error code line. It seems that "this.props.repository.contents_url.replace" will become undefined in some circumstances. We need figure out the stable reproduce steps.

**Comment by rancidfrog** [comment]
When not connected to internet.
Steps to reproduce:
Switch off data and wifi, click on link on feed to repository, then click on view code.
Just tested again and app crashes

**Comment by chinesedfan** [comment]
@rancidfrog Oh, I see. It is due to the repository can not be loaded. Maybe we need a network disconnected screen, or at least hide the view source item.

**Comment by rancidfrog** [comment]
The great thing about gitpoint is that you are able to navigate through everything that has been cached. Hiding stuff just complicates things in coding.
However, there should be a mechanism where if it not cached a toast should appear stating "Not connected" or something of that sort.

**Comment by chinesedfan** [comment]
Now we have `API Error` alert. Enjoy.
