### ISSUE TITLE
[1.5.0] Clicks recorded multiple times invoking multiple duplicate actions

### ISSUE THREAD

**Issue by rancidfrog** [gitpoint/git-point#669]
Clicking on "Options" or an "Issue" in feed quick enough, or when app lag maybe due to slow/bad connection, app opens up multiple requests to particular issue/options. Clicking back takes you to the same page you clicked on, in same cases three or four times.
```
12-19 11:24:46.094  3054  3054 D Launcher: onClick
12-19 11:24:46.096  1440  2971 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.gitpoint/.MainActivity bnds=[436,1081][645,1398] (has extras)} from uid 10074 pid 3054 on display 0
12-19 11:24:46.108  1440  2971 D ActivityTrigger: activityStartTrigger: Activity is Triggerred in full screen ApplicationInfo{8b18581 com.gitpoint}
12-19 11:24:46.108  1440  2971 E ActivityTrigger: activityStartTrigger: not whiteListedcom.gitpoint/com.gitpoint.MainActivity/6
12-19 11:24:46.108  1440  2971 D CompatibilityInfo: mCompatibilityFlags - 0
12-19 11:24:46.108  1440  2971 D CompatibilityInfo: applicationDensity - 380
12-19 11:24:46.108  1440  2971 D CompatibilityInfo: applicationScale - 1.0
12-19 11:24:46.110  1440  2971 D ActivityTrigger: activityResumeTrigger: The activity in ApplicationInfo{8b18581 com.gitpoint} is now in focus and seems to be in full-screen mode
12-19 11:24:46.110  1440  2971 E ActivityTrigger: activityResumeTrigger: not whiteListedcom.gitpoint/com.gitpoint.MainActivity/6
12-19 11:24:46.110  1440  2971 D ActivityTrigger: ActivityTrigger activityPauseTrigger
12-19 11:24:46.112  3054  3054 D Stats   : SaveStats onPreExecute isStatsChanged
12-19 11:24:46.112  3054  1879 D Stats   : SaveStats doInBackground...
12-19 11:24:46.113  3054  3054 D Launcher: onPause
12-19 11:24:46.115  1440 14791 D ActivityTrigger: activityResumeTrigger: The activity in ApplicationInfo{8b18581 com.gitpoint} is now in focus and seems to be in full-screen mode
12-19 11:24:46.115  1440 14791 E ActivityTrigger: activityResumeTrigger: not whiteListedcom.gitpoint/com.gitpoint.MainActivity/6
12-19 11:24:46.115  1440 14791 D EmbryoManager: Embryo claimed. com.gitpoint, pid=1726
12-19 11:24:46.115  1440 14791 D CompatibilityInfo: mCompatibilityFlags - 0
12-19 11:24:46.115  1440 14791 D CompatibilityInfo: applicationDensity - 380
12-19 11:24:46.115  1440 14791 D CompatibilityInfo: applicationScale - 1.0
12-19 11:24:46.119  1440 14791 D CompatibilityInfo: mCompatibilityFlags - 0
12-19 11:24:46.119  1440 14791 D CompatibilityInfo: applicationDensity - 380
12-19 11:24:46.119  1440 14791 D CompatibilityInfo: applicationScale - 1.0
12-19 11:24:46.121  1726  1726 V Font    : Change font:1
12-19 11:24:46.123  1726  1726 V fb-UnpackingSoSource: locked dso store /data/user/0/com.gitpoint/lib-main
12-19 11:24:46.123  1726  1726 I fb-UnpackingSoSource: dso store is up-to-date: /data/user/0/com.gitpoint/lib-main
12-19 11:24:46.123  1726  1726 V fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.gitpoint/lib-main
12-19 11:24:46.125  3054  3054 D Stats   : SaveStats onPreExecute onStatsChanged:
12-19 11:24:46.132  1726  1726 D ReactNative: [CodePush] Loading JS bundle from "assets://index.android.bundle"
12-19 11:24:46.133  1726  1726 D ReactNative: ReactInstanceManager.ctor()
12-19 11:24:46.135  1726  1726 D ReactNative: ReactInstanceManager.createReactContextInBackground()
12-19 11:24:46.135  1726  1726 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundInner()
12-19 11:24:46.135  1726  1726 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundFromBundleLoader()
12-19 11:24:46.139  3054  1879 D AppTracker: App Event: stop
12-19 11:24:46.141  1726  1726 I art     : Thread[1,tid=1726,Native,Thread*=0xea685400,peer=0x754fe268,"main"] recursive attempt to load library "/data/app/com.gitpoint-2/lib/arm/libfb.so"
12-19 11:24:46.142  1726  1726 D ReactNative: ReactInstanceManager.recreateReactContextInBackground()
12-19 11:24:46.142  1726  1726 D ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()
12-19 11:24:46.142  1726  2186 D ReactNative: ReactInstanceManager.createReactContext()
12-19 11:24:46.152  1726  2187 D AppTracker: App Event: start
12-19 11:24:46.154  1726  2186 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTGroupViewManager
12-19 11:24:46.155  1726  2186 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTGroupShadowNode
12-19 11:24:46.156  1726  2186 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTShapeViewManager
12-19 11:24:46.156  1726  2186 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTShapeShadowNode
12-19 11:24:46.157  1726  2186 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTTextViewManager
12-19 11:24:46.157  1726  2186 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTTextShadowNode
12-19 11:24:46.157  1726  2186 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDialogPickerManager
12-19 11:24:46.159  1726  2186 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.uimanager.LayoutShadowNode
12-19 11:24:46.161  1726  2186 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.drawer.ReactDrawerLayoutManager
12-19 11:24:46.161  3054  3054 D RecyclerViewWrapper: onWindowVisibilityChanged:8
12-19 11:24:46.163  1726  2186 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDropdownPickerManager
12-19 11:24:46.164  1726  2186 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollViewManager
12-19 11:24:46.166  1726  2186 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ReactProgressBarViewManager
12-19 11:24:46.168  1726  2186 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ProgressBarShadowNode
12-19 11:24:46.168  2231  2231 D PhoneStatusBar: setSystemUiVisibility vis=608 mask=ffffffff oldVal=2708 newVal=608 diff=2100
12-19 11:24:46.168  2231  2231 I StatusBarIconController: setIconsDark dark:false animate:true currentDark:true mTransitionPending:true mTransitionDeferring:false mPendingDarkIntensity:0.0
12-19 11:24:46.169  2231  2231 I StatusBarIconController: setIconTintInternal:1.0
12-19 11:24:46.169  1726  2186 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactScrollViewManager
12-19 11:24:46.172  1726  2186 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager
12-19 11:24:46.174  1726  2186 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager$ReactSliderShadowNode
12-19 11:24:46.174  1726  2186 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager
12-19 11:24:46.176  1726  2186 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager$ReactSwitchShadowNode
12-19 11:24:46.177  1726  2186 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.toolbar.ReactToolbarManager

12-19 11:24:46.179  1440  1509 I ActivityManager: Displayed com.gitpoint/.MainActivity: +64ms

12-19 11:24:46.180  1726  2186 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.webview.ReactWebViewManager
12-19 11:24:46.182  1726  2186 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.swiperefresh.SwipeRefreshLayoutManager
12-19 11:24:46.184  1726  2186 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewManager
12-19 11:24:46.185  1726  2186 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewShadowNode
12-19 11:24:46.185  1726  2186 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageViewManager
12-19 11:24:46.185  1726  2186 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageShadowNode
12-19 11:24:46.186  1726  2186 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.image.ReactImageManager
12-19 11:24:46.188  1726  2186 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ReactModalHostManager
12-19 11:24:46.189  1726  2186 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ModalHostShadowNode
12-19 11:24:46.189  1726  2186 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextManager
12-19 11:24:46.191  1726  2186 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextShadowNode
12-19 11:24:46.193  1726  2186 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputManager
12-19 11:24:46.196  2231  2231 I StatusBarIconController: setIconTintInternal:0.94172597
12-19 11:24:46.197  1726  2186 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputShadowNode
12-19 11:24:46.198  1726  2186 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextViewManager
12-19 11:24:46.198  1726  2186 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.view.ReactViewManager
12-19 11:24:46.201  1726  2186 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.viewpager.ReactViewPagerManager
12-19 11:24:46.203  1726  2186 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextViewManager
12-19 11:24:46.203  1726  2186 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.BV.LinearGradient.LinearGradientManager12-19 11:24:46.204  1726  2186 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.reactnative.photoview.PhotoViewManager

12-19 11:24:46.216  1726  2186 D ReactNative: Initializing React Xplat Bridge.
12-19 11:24:46.218  1726  2186 D ReactNative: Initializing React Xplat Bridge before initializeBridge
12-19 11:24:46.222  1726  2186 D ReactNative: Initializing React Xplat Bridge after initializeBridge
12-19 11:24:46.222  1726  2186 D ReactNative: CatalystInstanceImpl.runJSBundle()

12-19 11:24:46.239  1726  2192 D ReactNative: ReactInstanceManager.setupReactContext()
12-19 11:24:46.239  1726  2192 D ReactNative: CatalystInstanceImpl.initialize()
12-19 11:24:46.240  1726  2192 D ReactNative: ReactInstanceManager.attachRootViewToInstance()

12-19 11:24:46.382  3054  3054 D QuickPage: leaveQuickPageEditMode: true false false
12-19 11:24:46.383  3054  3054 D Launcher: mAppWidgetHost.stopListening()
12-19 11:24:46.553  1440  1508 D BluetoothManagerService: Message: 20
12-19 11:24:46.553  1440  1508 D BluetoothManagerService: Added callback: android.bluetooth.IBluetoothManagerCallback$Stub$Proxy@ed74b87:true
12-19 11:24:46.553  1726  2191 W System.err: java.lang.SecurityException: Need BLUETOOTH permission: Neither user 10152 nor current process has android.permission.BLUETOOTH.
12-19 11:24:46.553  1726  2191 W System.err:    at android.os.Parcel.readException(Parcel.java:1684)
12-19 11:24:46.553  1726  2191 W System.err:    at android.os.Parcel.readException(Parcel.java:1637)
12-19 11:24:46.553  1726  2191 W System.err:    at android.bluetooth.IBluetoothManager$Stub$Proxy.getName(IBluetoothManager.java:448)
12-19 11:24:46.553  1726  2191 W System.err:    at android.bluetooth.BluetoothAdapter.getName(BluetoothAdapter.java:1004)
12-19 11:24:46.553  1726  2191 W System.err:    at com.learnium.RNDeviceInfo.RNDeviceModule.getConstants(RNDeviceModule.java:106)
12-19 11:24:46.553  1726  2191 W System.err:    at com.facebook.react.bridge.JavaModuleWrapper.getConstants(JavaModuleWrapper.java:140)
12-19 11:24:46.553  1726  2191 W System.err:    at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
12-19 11:24:46.553  1726  2191 W System.err:    at android.os.Handler.handleCallback(Handler.java:751)
12-19 11:24:46.553  1726  2191 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:95)
12-19 11:24:46.553  1726  2191 W System.err:    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
12-19 11:24:46.553  1726  2191 W System.err:    at android.os.Looper.loop(Looper.java:154)
12-19 11:24:46.553  1726  2191 W System.err:    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
12-19 11:24:46.553  1726  2191 W System.err:    at java.lang.Thread.run(Thread.java:761)
12-19 11:24:47.066  1726  2191 I ReactNativeJS: Running application "GitPoint" with appParams: {"rootTag":1}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON
12-19 11:24:47.102  1726  2191 I ReactNativeJS: [CodePush] Checking for update.
12-19 11:24:47.103  1726  2191 I ReactNativeJS: [CodePush] Reporting binary update (1.4.1)
12-19 11:24:47.120   685  2831 E ANDR-PERF-OPTSHANDLER: perf_lock_rel: updated /sys/class/scsi_host/host0/../../../clkscale_enable with 1
12-19 11:24:47.120   685  2831 E ANDR-PERF-OPTSHANDLER:  return value 2
12-19 11:24:47.120   685  2831 E ANDR-PERF-RESOURCEQS: Failed to reset optimization [3, 0]
12-19 11:24:47.137  1726  2204 I art     : Starting a blocking GC AddRemoveAppImageSpace
12-19 11:24:47.138  1726  2204 W System  : ClassLoader referenced unknown path: /system/app/WebViewGoogle/lib/arm
12-19 11:24:47.144  1726  2204 D ApplicationLoaders: ignored Vulkan layer search path /system/app/WebViewGoogle/lib/arm:/system/app/WebViewGoogle/WebViewGoogle.apk!/lib/armeabi-v7a:/system/lib:/vendor/lib for namespace 0xed081090
12-19 11:24:47.147  1726  2204 I WebViewFactory: Loading com.google.android.webview version 58.0.3029.83 (code 302908350)
12-19 11:24:47.180  1726  2204 I cr_LibraryLoader: Time to load native libraries: 12 ms (timestamps 5379-5391)
12-19 11:24:47.186  1726  2204 I chromium: [INFO:library_loader_hooks.cc(140)] Chromium logging enabled: level = 0, default verbosity = 0
12-19 11:24:47.186  1726  2204 I cr_LibraryLoader: Expected native library version number "58.0.3029.83", actual native library version number "58.0.3029.83"
12-19 11:24:48.636  1726  2192 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextShadowNode
12-19 11:24:48.756  1726  2191 I ReactNativeJS: [CodePush] Report status failed: {"previousLabelOrAppVersion":"1.4.0","appVersion":"1.4.1"}
12-19 11:24:48.759  1726  1737 I art     : Do partial code cache collection, code=27KB, data=30KB
12-19 11:24:48.759  1726  1737 I art     : After code cache collection, code=24KB, data=28KB
12-19 11:24:48.759  1726  1737 I art     : Increasing code cache capacity to 128KB
12-19 11:24:48.762  1726  2191 I ReactNativeJS: [CodePush] An unknown error occurred.
12-19 11:24:48.762  1726  2191 I ReactNativeJS: [CodePush] Network request failed

```
Also, in log above, there is error regarding bluetooth? Why request for bluetooth?

**Comment by machour** [comment]
@rancidfrog about the BLUETOOTH mention, we do not request the permission in the app, but maybe react-native tries it as a way to obtain an internet connection? 🤔

**Comment by chinesedfan** [comment]
Is there any throttle mechanism on button clicks? This is an interesting question.
