### ISSUE TITLE
Paths relative to src are not resolved

### ISSUE THREAD

**Issue by vadimkorr** [gitpoint/git-point#812]
| Question         | Response    |
| ---------------- | ----------- |
| Version?         | v1.4.1      |
| Devices tested?  | Android 6.0.0 (API 23) Google Nexus 6 emulator |

---

## What Currently Happens?

Cannot run app, caused by paths relative to 'src' folder

## What Do You Expect To Happen?

Launched succesfully

## My Reproduction Steps

1. react-native run-android
2. Build 100%, on launching the app causes the following error:

```
The development server returned response error code: 500

URL: http://10.0.3.2:8081/index.delta?platform=android&dev=true&minify=false

Body:
{
  "originModulePath": "D:\\proj\\github\\git-point\\App.js",
  "targetModuleName": "config",
  "message": "Unable to resolve module `config` from `D:\\proj\\github\\git-point\\App.js`: Module does not exist in the module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.",
  "errors": [
    {
      "description": "Unable to resolve module `config` from `D:\\proj\\github\\git-point\\App.js`: Module does not exist in the module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`."
    }
  ],
  "name": "Error",
  "stack": "Error: Unable to resolve module `config` from `D:\\proj\\github\\git-point\\App.js`: Module does not exist in the module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.\n    at ModuleResolver.resolveDependency (D:\\proj\\github\\git-point\\node_modules\\metro\\src\\node-haste\\DependencyGraph\\ModuleResolution.js:158:1476)\n    at ResolutionRequest.resolveDependency (D:\\proj\\github\\git-point\\node_modules\\metro\\src\\node-haste\\DependencyGraph\\ResolutionRequest.js:92:16)\n    at DependencyGraph.resolveDependency (D:\\proj\\github\\git-point\\node_modules\\metro\\src\\node-haste\\DependencyGraph.js:271:4465)\n    at dependencies.map.relativePath (D:\\proj\\github\\git-point\\node_modules\\metro\\src\\DeltaBundler\\traverseDependencies.js:379:19)\n    at Array.map (<anonymous>)\n    at resolveDependencies (D:\\proj\\github\\git-point\\node_modules\\metro\\src\\DeltaBundler\\traverseDependencies.js:378:16)\n    at D:\\proj\\github\\git-point\\node_modules\\metro\\src\\DeltaBundler\\traverseDependencies.js:203:33\n    at Generator.next (<anonymous>)\n    at step (D:\\proj\\github\\git-point\\node_modules\\metro\\src\\DeltaBundler\\traverseDependencies.js:296:307)\n    at D:\\proj\\github\\git-point\\node_modules\\metro\\src\\DeltaBundler\\traverseDependencies.js:296:467"
}
processBundleResult
    BundleDownloader.java:231
access$100
    BundleDownloader.java:37
onResponse
    BundleDownloader.java:204
execute
    RealCall.java:135
run
    NamedRunnable.java:32
runWorker
    ThreadPoolExecutor.java:1113
run
    ThreadPoolExecutor.java:588
run
    Thread.java:818

```

**Comment by chinesedfan** [comment]
@vadimkorr This is usually due to your local development environment. Please try steps mentioned in your log, i.e.

```
To resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`
```

**Comment by vadimkorr** [comment]
@chinesedfan, thanks for reply
Solved the problem by the following way:
1. Opened PowerShell as admin, run `npm start -- --reset-cache`
2. Opened another PowerShell, run `react-native run-android`
